"""removed hash column files

Revision ID: 8843d5fe4f1b
Revises: 9830694260df
Create Date: 2026-03-04 14:47:09.019109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8843d5fe4f1b'
down_revision: Union[str, None] = '9830694260df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_hash', schema='ecp_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_hash', sa.String(length=255), nullable=True), schema='ecp_events')
    # ### end Alembic commands ###
